spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=restaurant
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServer2008Dialect

  thymeleaf:
     mode: HTML5
     content-type: text/html
     cache: false
server:
  port: 8090

